{
 "title": "Energy",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Devices",
    "query": "SHOW TAG VALUES from \"power\" WITH KEY IN (\"device_type\")"
   },
   { "name": "price_iva", "label": "IVA", "query": "${VAR_PRICE_IVA}" },
   {
    "name": "price_ref_kwh_peak",
    "label": "Referencia Preço KWh - Fora Vazio",
    "query": "0.1587"
   },
   { "name": "price_ref_kwh_offpeak", "label": "Referência Preço KWh - Vazio", "query": "0.1587" },
   { "name": "price_ref_daily", "label": "Referência Preço Diário", "query": "0.3909" },
   { "name": "sample", "query": "${VAR_SAMPLE}" },
   { "name": "sample_seconds", "query": "${VAR_SAMPLE_SECONDS}" },
   {
    "name": "invoice_month",
    "label": "Mês de Lançamento",
    "query": "SHOW TAG VALUES from \"power\" WITH KEY IN (\"invoice_month\")"
   },
   {
    "name": "invoice_year",
    "label": "Ano de Lançamento",
    "query": "SHOW TAG VALUES from \"power\" WITH KEY IN (\"invoice_year\")"
   }
  ]
 },
 "panels": [
  { "title": "Consumos $device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "device" },
  {
   "title": "Amperes (now)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"amp\")  FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumos",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 15, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Fora de Vazio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power_d",
     "query": "SELECT sum(\"kwh\") as \"kwhd\" FROM ( SELECT sum(\"watt\") / 1000 * mode(\"time\") / 3600 as \"kwh\" FROM ( SELECT elapsed(mean(\"power\"),1s) as \"time\", mean(\"power\") as \"watt\" FROM \"power\" WHERE (\"deviceId\" =~ /^$device$/) AND \"trange\" = 'FVZ' AND $timeFilter GROUP BY time($sample_s) ) GROUP BY time(1h) )  GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "kwh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "tarif", "operator": "=", "value": "peak" },
      { "condition": "AND", "key": "invoice_year", "operator": "=~", "value": "/^$invoice_year$/" },
      { "condition": "AND", "key": "invoice_month", "operator": "=~", "value": "/^$invoice_month$/" }
     ]
    },
    {
     "alias": "Vazio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power_d",
     "query": "SELECT sum(\"kwh\") as \"kwhd\" FROM ( SELECT sum(\"watt\") / 1000 * mode(\"time\") / 3600 as \"kwh\" FROM ( SELECT elapsed(mean(\"power\"),1s) as \"time\", mean(\"power\") as \"watt\" FROM \"power\" WHERE (\"deviceId\" =~ /^$device$/) AND \"trange\" = 'VZ' AND $timeFilter GROUP BY time($sample_s) ) GROUP BY time(1h) )  GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "kwh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "tarif", "operator": "=", "value": "offpeak" },
      { "condition": "AND", "key": "invoice_year", "operator": "=~", "value": "/^$invoice_year$/" },
      { "condition": "AND", "key": "invoice_month", "operator": "=~", "value": "/^$invoice_month$/" }
     ]
    }
   ]
  },
  {
   "title": "Valor Final c/IVA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"price\") + last(\"daily_price\") + ( ( sum(\"price\") + last(\"daily_price\") ) * ($price_iva / 100) ) FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Tarifa",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT last(\"watt_offpeek\") - last(\"watt_peek\") as \"result\" FROM (SELECT last(\"watt_peek\") as \"watt_peek\" FROM (SELECT last(\"power\") as \"watt_peek\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^main$/) AND $timeFilter AND \"tarif\" = 'peak' GROUP BY time($sample_seconds) fill(previous))),(SELECT last(\"watt_offpeek\") as \"watt_offpeek\" FROM (SELECT last(\"power\") as \"watt_offpeek\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^main$/) AND $timeFilter AND \"tarif\" = 'offpeak' GROUP BY time($sample_seconds) fill(previous))) fill(0)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Preço Atual por Kwh",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "power_d",
     "query": "SELECT \"kwh_price\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Preço Atual Diário",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "power_d",
     "query": "SELECT \"daily_price\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Valor Final KWh c/IVA",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "power_d",
     "query": "SELECT \"price\" + ( \"price\" * ($price_iva / 100) ) FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Valor Final",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"price\") + last(\"daily_price\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumo KWh Ano",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "kwatth", "label": "KWh" }
   ],
   "targets": [
    {
     "alias": "$tag_invoice_year-$tag_invoice_month",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"kwh\") as \"kwh\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/)  AND (\"invoice_year\" =~ /^$invoice_year$/) AND $timeFilter GROUP BY \"invoice_month\", \"invoice_year\"",
     "select": [
      [
       { "params": [ "kwh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=", "value": "main" },
      { "condition": "AND", "key": "tarif", "operator": "=", "value": "offpeak" }
     ]
    }
   ]
  },
  {
   "title": "Custo KWh Ano",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "currencyEUR", "label": "KWh" }
   ],
   "targets": [
    {
     "alias": "$tag_invoice_year-$tag_invoice_month",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"price\") as \"price\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/)  AND (\"invoice_year\" =~ /^$invoice_year$/) AND $timeFilter GROUP BY \"invoice_month\", \"invoice_year\"",
     "select": [
      [
       { "params": [ "kwh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=", "value": "main" },
      { "condition": "AND", "key": "tarif", "operator": "=", "value": "offpeak" }
     ]
    }
   ]
  },
  {
   "title": "Consumo Watt",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "watt", "label": "Watt" }
   ],
   "targets": [
    {
     "alias": "Consumo (W) - Vazio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"power\") FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif = 'offpeak' GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "Consumo (W) - Fora Vazio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"power\") FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif = 'peak' GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "Consumo (KWh)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT cumulative_sum(\"kwh\") FROM (SELECT sum(\"watt\") / 1000 * mode(\"time\") / 3600 as \"kwh\" FROM ( SELECT elapsed(mean(\"power\"),1s) as \"time\", mean(\"power\") as \"watt\" FROM \"power\" WHERE (\"deviceId\" =~ /^$device$/) AND $timeFilter GROUP BY time($sample_s) ) GROUP BY time(1h) )",
     "select": [
      [
       { "params": [ "kwh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "invoice_year", "operator": "=~", "value": "/^$invoice_year$/" },
      { "condition": "AND", "key": "invoice_month", "operator": "=~", "value": "/^$invoice_month$/" }
     ]
    },
    {
     "alias": "Consumo (W) - Devices",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"power\") FROM \"raw_data\".\"power\" WHERE  (\"device_type\" != 'main') AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/)  AND $timeFilter GROUP BY time($interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Consumo (W) - Fora de Fatura",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"power\") FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND ( \"invoice_year\" !~ /^$invoice_year$/ OR \"invoice_month\" !~ /^$invoice_month$/ ) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=", "value": "main" },
      { "condition": "AND", "key": "invoice_year", "operator": "!~", "value": "/^$invoice_year$/" }
     ]
    }
   ]
  },
  {
   "title": "Now (W)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT \"power\" FROM \"power\" WHERE (\"deviceId\" =~ /^$device$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT \"power\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND \"power\" > 0",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"power\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT \"power\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"power\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Amp / Volt",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "amp", "label": "Amperes" }
   ],
   "targets": [
    {
     "alias": "Amperes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"amp\") FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/ AND \"invoice_year\" =~ /^$invoice_year$/ AND \"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "amp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "invoice_year", "operator": "=~", "value": "/^$invoice_year$/" },
      { "condition": "AND", "key": "invoice_month", "operator": "=~", "value": "/^$invoice_month$/" }
     ]
    },
    {
     "alias": "Volts",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"volt\") FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/ AND \"volt\" > 0 AND \"invoice_year\" =~ /^$invoice_year$/ AND \"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "volt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "volt", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "invoice_year", "operator": "=~", "value": "/^$invoice_year$/" },
      { "condition": "AND", "key": "invoice_month", "operator": "=~", "value": "/^$invoice_month$/" }
     ]
    },
    {
     "alias": "Amperes Fora da Fatura",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"amp\") FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/ AND ( \"invoice_year\" !~ /^$invoice_year$/ OR \"invoice_month\" !~ /^$invoice_month$/ )) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Now (Amp)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT last(\"amp\")  FROM \"power\" WHERE (\"deviceId\" =~ /^$device$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "amp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT \"amp\" FROM \"raw_data\".\"power\" WHERE  (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND \"amp\" > 0",
     "select": [
      [
       { "params": [ "amp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT \"amp\" FROM \"raw_data\".\"power\" WHERE  (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "amp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT \"amp\" FROM \"raw_data\".\"power\" WHERE  (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "amp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=", "value": "main" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT \"amp\" FROM \"raw_data\".\"power\" WHERE  (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "amp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumo KWh",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "kwatth", "label": "KWh" }
   ],
   "targets": [
    {
     "alias": "Consumo (KWh) - Fora de Vazio",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"kwh\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'peak' AND $timeFilter GROUP BY time(1d) fill(0)",
     "select": [
      [
       { "params": [ "kwh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=", "value": "main" },
      { "condition": "AND", "key": "tarif", "operator": "=", "value": "offpeak" }
     ]
    },
    {
     "alias": "Consumo (KWh) - Vazio",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"kwh\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'offpeak' AND $timeFilter GROUP BY time(1d) fill(0)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "Consumo (KWh)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"kwh\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Consumo (€)",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_d",
     "query": "SELECT sum(\"price\") FROM ( SELECT sum(\"kwh\") * $price_kwh_fvz as \"price\" FROM ( SELECT sum(\"watt\") / 1000 * mode(\"time\")  / 3600 as \"kwh\" FROM ( SELECT elapsed(mean(\"power\"),1s) as \"time\", mean(\"power\") as \"watt\" FROM \"power\" WHERE (\"deviceId\" =~ /^$device$/) AND $timeFilter AND \"trange\" = 'FVZ' GROUP BY time($sample_s) ) GROUP BY time(1h) )  GROUP BY time(1d) ) , ( SELECT sum(\"kwh\")  * $price_kwh_vz as \"price\" FROM ( SELECT sum(\"watt\") / 1000 * mode(\"time\")  / 3600 as \"kwh\" FROM ( SELECT elapsed(mean(\"power\"),1s) as \"time\", mean(\"power\") as \"watt\" FROM \"power\" WHERE (\"deviceId\" =~ /^$device$/) AND $timeFilter AND \"trange\" = 'VZ' GROUP BY time($sample_s) ) GROUP BY time(1h) )  GROUP BY time(1d) ) GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "invoice_year", "operator": "=~", "value": "/^$invoice_year$/" },
      { "condition": "AND", "key": "invoice_month", "operator": "=~", "value": "/^$invoice_month$/" }
     ]
    },
    {
     "alias": "Consumo (KWh) - Fora da Fatura",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"kwh\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND ( \"invoice_year\" !~ /^$invoice_year$/ OR \"invoice_month\" !~ /^$invoice_month$/ ) AND $timeFilter GROUP BY time(1d) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Now (KWh)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"kwh\") as \"kwh\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "kwh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"kwh\") as \"kwh\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"kwh\") as \"kwh\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT sum(\"kwh\") as \"kwh\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "kwh" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"kwh\") as \"kwh\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Vazio Vs Fora Vazio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "currencyEUR", "label": "Diferença Preço (€)" }
   ],
   "targets": [
    {
     "alias": "Reultado Negativo",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT \"result\" FROM ( SELECT sum(\"price_offpeek\") - sum(\"price_peek\") as \"result\"  FROM ( SELECT sum(\"price\") as \"price_peek\"  FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'peak' AND $timeFilter GROUP BY time(1d) fill(null) ) , ( SELECT sum(\"price\") as \"price_offpeek\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'offpeak' AND $timeFilter GROUP BY time(1d) fill(null) ) GROUP BY time(1d)  fill(0) ) WHERE \"result\" < 0",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "Resultado Positivo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"result\" FROM ( SELECT sum(\"price_offpeek\") - sum(\"price_peek\") as \"result\"  FROM ( SELECT sum(\"price\") as \"price_peek\"  FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'peak' AND $timeFilter GROUP BY time(1d) fill(null) ) , ( SELECT sum(\"price\") as \"price_offpeek\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'offpeak' AND $timeFilter GROUP BY time(1d) fill(null) ) GROUP BY time(1d)  fill(0) ) WHERE \"result\" >= 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Consumo (€)",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"price\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "Resultado Fora da Fatura",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"result\" FROM ( SELECT sum(\"price_offpeek\") - sum(\"price_peek\") as \"result\"  FROM ( SELECT sum(\"price\") as \"price_peek\"  FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND ( \"invoice_year\" !~ /^$invoice_year$/ OR \"invoice_month\" !~ /^$invoice_month$/ ) AND \"tarif\" = 'peak' AND $timeFilter GROUP BY time(1d) fill(null) ) , ( SELECT sum(\"price\") as \"price_offpeek\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND ( \"invoice_year\" !~ /^$invoice_year$/ OR \"invoice_month\" !~ /^$invoice_month$/ ) AND \"tarif\" = 'offpeak' AND $timeFilter GROUP BY time(1d) fill(null) ) GROUP BY time(1d)  fill(0) )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT \"watt_offpeek\" - \"watt_peek\" as \"result\" FROM (SELECT last(\"watt_peek\") as \"watt_peek\" FROM (SELECT last(\"power\") as \"watt_peek\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^main$/) AND $timeFilter AND \"tarif\" = 'peak' GROUP BY time($sample_seconds) fill(previous))),(SELECT last(\"watt_offpeek\") as \"watt_offpeek\" FROM (SELECT last(\"power\") as \"watt_offpeek\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^main$/) AND $timeFilter AND \"tarif\" = 'offpeak' GROUP BY time($sample_seconds) fill(previous))) fill(0)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT \"result\" FROM ( SELECT sum(\"price_offpeek\") - sum(\"price_peek\") as \"result\"  FROM ( SELECT sum(\"price\") as \"price_peek\"  FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'peak' AND $timeFilter GROUP BY time(1d) fill(null) ) , ( SELECT sum(\"price\") as \"price_offpeek\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'offpeak' AND $timeFilter GROUP BY time(1d) fill(null) ) GROUP BY time(1d)  fill(0) ) ",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT \"result\" FROM ( SELECT sum(\"price_offpeek\") - sum(\"price_peek\") as \"result\"  FROM ( SELECT sum(\"price\") as \"price_peek\"  FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'peak' AND $timeFilter GROUP BY time(1d) fill(null) ) , ( SELECT sum(\"price\") as \"price_offpeek\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'offpeak' AND $timeFilter GROUP BY time(1d) fill(null) ) GROUP BY time(1d)  fill(0) ) ",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT \"result\" FROM ( SELECT sum(\"price_offpeek\") - sum(\"price_peek\") as \"result\"  FROM ( SELECT sum(\"price\") as \"price_peek\"  FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'peak' AND $timeFilter GROUP BY time(1d) fill(null) ) , ( SELECT sum(\"price\") as \"price_offpeek\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'offpeak' AND $timeFilter GROUP BY time(1d) fill(null) ) GROUP BY time(1d)  fill(0) ) ",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT \"result\" FROM ( SELECT sum(\"price_offpeek\") - sum(\"price_peek\") as \"result\"  FROM ( SELECT sum(\"price\") as \"price_peek\"  FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'peak' AND $timeFilter GROUP BY time(1d) fill(null) ) , ( SELECT sum(\"price\") as \"price_offpeek\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND \"tarif\" = 'offpeak' AND $timeFilter GROUP BY time(1d) fill(null) ) GROUP BY time(1d)  fill(0) ) ",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Plano Vs Referência",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "currencyEUR", "label": "Euro" }
   ],
   "targets": [
    {
     "alias": "Ganhos (€)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"result\" FROM (SELECT (sum(\"ref_cons_offpeak\") + sum(\"ref_cons_peak\") + $price_ref_daily) - (sum(\"cons\") + last(\"daily_price\")) as \"result\" FROM (SELECT sum(\"kwh\") * last(\"kwh_price\") as cons, last(\"daily_price\") as \"daily_price\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d), * fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_peak as ref_cons_peak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='peak' GROUP BY time(1d) fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_offpeak as ref_cons_offpeak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='offpeak' GROUP BY time(1d) fill(null)) GROUP BY time(1d) fill(null)) WHERE \"result\" > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Perdas (€)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"result\" FROM (SELECT (sum(\"ref_cons_offpeak\") + sum(\"ref_cons_peak\") + $price_ref_daily) - (sum(\"cons\") + last(\"daily_price\")) as \"result\" FROM (SELECT sum(\"kwh\") * last(\"kwh_price\") as cons, last(\"daily_price\") as \"daily_price\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d), * fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_peak as ref_cons_peak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='peak' GROUP BY time(1d) fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_offpeak as ref_cons_offpeak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='offpeak' GROUP BY time(1d) fill(null)) GROUP BY time(1d) fill(null)) WHERE \"result\" < 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Resultados Fora da Fatura",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"result\" FROM (SELECT (sum(\"ref_cons_offpeak\") + sum(\"ref_cons_peak\") + $price_ref_daily) - (sum(\"cons\") + last(\"daily_price\")) as \"result\" FROM (SELECT sum(\"kwh\") * last(\"kwh_price\") as cons, last(\"daily_price\") as \"daily_price\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND ( \"invoice_year\" !~ /^$invoice_year$/ OR \"invoice_month\" !~ /^$invoice_month$/ ) AND $timeFilter GROUP BY time(1d), * fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_peak as ref_cons_peak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND ( \"invoice_year\" !~ /^$invoice_year$/ OR \"invoice_month\" !~ /^$invoice_month$/ ) AND $timeFilter AND tarif='peak' GROUP BY time(1d) fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_offpeak as ref_cons_offpeak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND ( \"invoice_year\" !~ /^$invoice_year$/ OR \"invoice_month\" !~ /^$invoice_month$/ ) AND $timeFilter AND tarif='offpeak' GROUP BY time(1d) fill(null)) GROUP BY time(1d) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Now (€)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT \"result\" FROM (SELECT (sum(\"ref_cons_offpeak\") + sum(\"ref_cons_peak\") + $price_ref_daily) - (sum(\"cons\") + last(\"daily_price\")) as \"result\" FROM (SELECT sum(\"kwh\") * last(\"kwh_price\") as cons, last(\"daily_price\") as \"daily_price\" FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND $timeFilter GROUP BY time(1d), * fill(0)), (SELECT sum(\"kwh\") * $price_ref_kwh_peak as ref_cons_peak FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND $timeFilter AND tarif='peak' GROUP BY time(1d) fill(0)), (SELECT sum(\"kwh\") * $price_ref_kwh_offpeak as ref_cons_offpeak FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND $timeFilter AND tarif='offpeak' GROUP BY time(1d) fill(0)) GROUP BY time(1d) fill(0))",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000 * 24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "main" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT \"result\" FROM (SELECT (sum(\"ref_cons_offpeak\") + sum(\"ref_cons_peak\") + $price_ref_daily) - (sum(\"cons\") + last(\"daily_price\")) as \"result\" FROM (SELECT sum(\"kwh\") * last(\"kwh_price\") as cons, last(\"daily_price\") as \"daily_price\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d), * fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_peak as ref_cons_peak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='peak' GROUP BY time(1d) fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_offpeak as ref_cons_offpeak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='offpeak' GROUP BY time(1d) fill(null)) GROUP BY time(1d) fill(null))",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT \"result\" FROM (SELECT (sum(\"ref_cons_offpeak\") + sum(\"ref_cons_peak\") + $price_ref_daily) - (sum(\"cons\") + last(\"daily_price\")) as \"result\" FROM (SELECT sum(\"kwh\") * last(\"kwh_price\") as cons, last(\"daily_price\") as \"daily_price\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d), * fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_peak as ref_cons_peak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='peak' GROUP BY time(1d) fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_offpeak as ref_cons_offpeak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='offpeak' GROUP BY time(1d) fill(null)) GROUP BY time(1d) fill(null))",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT \"result\" FROM (SELECT (sum(\"ref_cons_offpeak\") + sum(\"ref_cons_peak\") + $price_ref_daily) - (sum(\"cons\") + last(\"daily_price\")) as \"result\" FROM (SELECT sum(\"kwh\") * last(\"kwh_price\") as cons, last(\"daily_price\") as \"daily_price\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d), * fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_peak as ref_cons_peak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='peak' GROUP BY time(1d) fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_offpeak as ref_cons_offpeak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='offpeak' GROUP BY time(1d) fill(null)) GROUP BY time(1d) fill(null))",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT \"result\" FROM (SELECT (sum(\"ref_cons_offpeak\") + sum(\"ref_cons_peak\") + $price_ref_daily) - (sum(\"cons\") + last(\"daily_price\")) as \"result\" FROM (SELECT sum(\"kwh\") * last(\"kwh_price\") as cons, last(\"daily_price\") as \"daily_price\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d), * fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_peak as ref_cons_peak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='peak' GROUP BY time(1d) fill(null)), (SELECT sum(\"kwh\") * $price_ref_kwh_offpeak as ref_cons_offpeak FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter AND tarif='offpeak' GROUP BY time(1d) fill(null)) GROUP BY time(1d) fill(null))",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumo Euro",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "currencyEUR", "label": "Euro" }
   ],
   "targets": [
    {
     "alias": "Consumo Diário (€) - Fora de Vazio",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_d",
     "query": "SELECT sum(\"kwh\") * $price_kwh_fvz FROM ( SELECT sum(\"watt\") / 1000 * mode(\"time\")  / 3600 as \"kwh\" FROM ( SELECT elapsed(mean(\"power\"),1s) as \"time\", mean(\"power\") as \"watt\" FROM \"power\" WHERE (\"deviceId\" =~ /^$device$/) AND \"trange\" = 'FVZ' AND $timeFilter GROUP BY time($sample_s) ) GROUP BY time(1h)  )  GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "tarif", "operator": "=", "value": "peak" },
      { "condition": "AND", "key": "invoice_year", "operator": "=~", "value": "/^$invoice_year$/" },
      { "condition": "AND", "key": "invoice_month", "operator": "=~", "value": "/^$invoice_month$/" }
     ]
    },
    {
     "alias": "Consumo Diário (€) - Vazio",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_d",
     "query": "SELECT sum(\"kwh\") * $price_kwh_vz FROM ( SELECT sum(\"watt\") / 1000 * mode(\"time\")  / 3600 as \"kwh\" FROM ( SELECT elapsed(mean(\"power\"),1s) as \"time\", mean(\"power\") as \"watt\" FROM \"power\" WHERE (\"deviceId\" =~ /^$device$/) AND \"trange\" = 'VZ' AND $timeFilter GROUP BY time($sample_s) ) GROUP BY time(1h) )  GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "tarif", "operator": "=", "value": "offpeak" },
      { "condition": "AND", "key": "invoice_year", "operator": "=~", "value": "/^$invoice_year$/" },
      { "condition": "AND", "key": "invoice_month", "operator": "=~", "value": "/^$invoice_month$/" }
     ]
    },
    {
     "alias": "Consumo Diário (€)",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_d",
     "query": "SELECT sum(\"price\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/ AND \"invoice_year\" =~ /^$invoice_year$/ AND \"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_type", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "invoice_year", "operator": "=~", "value": "/^$invoice_year$/" },
      { "condition": "AND", "key": "invoice_month", "operator": "=~", "value": "/^$invoice_month$/" }
     ]
    },
    {
     "alias": "Potência Contratada (€)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"watt\") * last(\"daily_price\")  FROM ( SELECT mean(\"power\") as \"watt\", last(\"daily_price\") as \"daily_price\" FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d) fill(null) ) GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Consumos Fora da Fatura",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"price\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/ AND ( \"invoice_year\" !~ /^$invoice_year$/ OR \"invoice_month\" !~ /^$invoice_month$/ )) AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Now (€)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT sum(\"price\") + last(\"daily_price\") FROM \"raw_data\".\"power\" WHERE (\"device_type\" =~ /^$device$/) AND $timeFilter GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000 * 24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "main" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"price\") + last(\"daily_price\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"price\") + last(\"daily_price\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"price\") + last(\"daily_price\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"price\") + last(\"daily_price\") FROM \"storage\".\"power_d\" WHERE (\"device_type\" =~ /^$device$/) AND (\"invoice_year\" =~ /^$invoice_year$/) AND (\"invoice_month\" =~ /^$invoice_month$/) AND $timeFilter GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  }
 ]
}